name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: windows-latest
            platform: win32
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - name: run Chocolatey
        if: ${{ matrix.platform == 'win32' }}
        run: |
          choco install magicsplat-tcl-tk -y --version=1.16.0
          choco upgrade llvm
          refreshenv
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.platform == 'win32' }}
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
      - run: npm test
